##########################################################################
#                           Palindrome-Detector                          #
##########################################################################
version: '3'
services:
  mongodb:
    restart: always
    image: 'mongo:latest'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
  parse-server:
    image: 'parseplatform/parse-server:3.1.1'
    ports:
      - 1337:1337
    depends_on:
      - mongodb
    links:
      - mongodb
    command: --appId appId --masterKey masterKey --databaseURI 'mongodb://mongodb:27017/palindrome-detector'
