##########################################################################
#                           Palindrome-Detector                          #
##########################################################################
version: '3'
services:
  mongodb:
    restart: always
    image: 'mongo:latest'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROD=true
      - PORT=80
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 80:80
